"""
Report Store - Report storage with version management

Design:
- File-based storage (dev) / Object storage (production)
- Version history for each dimension
- Lightweight index in state, full content stored externally
- Supports time-travel (version rollback)
"""

import json
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, TypedDict

from ..utils.logger import get_logger
from ..utils.paths import get_data_dir

logger = get_logger(__name__)


# ==========================================
# TypedDict Definitions
# ==========================================

class ReportVersion(TypedDict):
    """Report version metadata (lightweight, stored in state)"""
    version: int              # 1-based version number
    report_id: str            # UUID generated by save()
    summary: str              # First 200 chars of content
    generated_at: str         # ISO timestamp
    revision_trigger: Optional[str]  # Reason for revision (e.g., "user feedback")


# ==========================================
# ReportStore Class
# ==========================================

class ReportStore:
    """
    Report Storage and Version Management

    Storage pattern:
        data/reports/{session_id}/{dim_key}/v{version}.md
        data/reports/{session_id}/{dim_key}/metadata.json

    Interface:
        - save() -> report_id
        - get() -> full content
        - list_versions() -> [ReportVersion, ...]
    """

    _instance: Optional["ReportStore"] = None

    def __init__(self, base_dir: Optional[Path] = None):
        """Initialize report store with base directory"""
        if base_dir is None:
            base_dir = get_data_dir() / "reports"
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"[ReportStore] Initialized at: {self.base_dir}")

    @classmethod
    def get_instance(cls) -> "ReportStore":
        """Get singleton instance"""
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def _get_dim_dir(self, session_id: str, dim_key: str) -> Path:
        """Get dimension directory path"""
        dim_dir = self.base_dir / session_id / dim_key
        dim_dir.mkdir(parents=True, exist_ok=True)
        return dim_dir

    async def save(
        self,
        session_id: str,
        dim_key: str,
        version: int,
        content: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Save report and return report_id

        Args:
            session_id: Session identifier
            dim_key: Dimension key (e.g., "location", "land_use")
            version: Version number (1-based)
            content: Full report content
            metadata: Optional metadata (revision_reason, etc.)

        Returns:
            report_id: UUID for retrieving the report
        """
        report_id = str(uuid.uuid4())
        dim_dir = self._get_dim_dir(session_id, dim_key)

        # Save content
        content_file = dim_dir / f"v{version}.md"
        content_file.write_text(content, encoding="utf-8")

        # Generate summary
        summary = content[:200] if len(content) > 200 else content

        # Build version metadata
        version_meta = ReportVersion(
            version=version,
            report_id=report_id,
            summary=summary,
            generated_at=datetime.utcnow().isoformat() + "Z",
            revision_trigger=metadata.get("revision_reason") if metadata else None,
        )

        # Update metadata.json
        meta_file = dim_dir / "metadata.json"
        versions = []
        if meta_file.exists():
            try:
                versions = json.loads(meta_file.read_text())
            except json.JSONDecodeError:
                logger.warning(f"[ReportStore] Corrupted metadata: {meta_file}")

        versions.append(version_meta)
        meta_file.write_text(json.dumps(versions, ensure_ascii=False, indent=2), encoding="utf-8")

        logger.info(f"[ReportStore] Saved: {session_id}/{dim_key}/v{version} (id={report_id[:8]}...)")
        return report_id

    async def get(self, report_id: str) -> Optional[str]:
        """
        Get full report content by report_id

        Args:
            report_id: UUID from save()

        Returns:
            Full content or None if not found
        """
        # Search for report_id across all sessions/dimensions
        for session_dir in self.base_dir.iterdir():
            if not session_dir.is_dir():
                continue
            for dim_dir in session_dir.iterdir():
                if not dim_dir.is_dir():
                    continue
                meta_file = dim_dir / "metadata.json"
                if not meta_file.exists():
                    continue
                try:
                    versions = json.loads(meta_file.read_text())
                    for v in versions:
                        if v.get("report_id") == report_id:
                            version = v.get("version")
                            content_file = dim_dir / f"v{version}.md"
                            if content_file.exists():
                                return content_file.read_text(encoding="utf-8")
                except json.JSONDecodeError:
                    continue

        logger.warning(f"[ReportStore] Not found: {report_id[:8]}...")
        return None

    async def get_by_version(
        self,
        session_id: str,
        dim_key: str,
        version: int
    ) -> Optional[str]:
        """
        Get report content by version number

        Args:
            session_id: Session identifier
            dim_key: Dimension key
            version: Version number

        Returns:
            Full content or None
        """
        dim_dir = self._get_dim_dir(session_id, dim_key)
        content_file = dim_dir / f"v{version}.md"
        if content_file.exists():
            return content_file.read_text(encoding="utf-8")
        return None

    async def get_latest(
        self,
        session_id: str,
        dim_key: str
    ) -> Optional[str]:
        """
        Get latest version content

        Args:
            session_id: Session identifier
            dim_key: Dimension key

        Returns:
            Full content of latest version or None
        """
        versions = await self.list_versions(session_id, dim_key)
        if not versions:
            return None
        latest_version = versions[-1].get("version", 0)
        return await self.get_by_version(session_id, dim_key, latest_version)

    async def list_versions(
        self,
        session_id: str,
        dim_key: str
    ) -> List[ReportVersion]:
        """
        List all versions for a dimension

        Args:
            session_id: Session identifier
            dim_key: Dimension key

        Returns:
            List of ReportVersion (sorted by version number)
        """
        dim_dir = self.base_dir / session_id / dim_key
        meta_file = dim_dir / "metadata.json"

        if not meta_file.exists():
            return []

        try:
            versions = json.loads(meta_file.read_text())
            versions.sort(key=lambda v: v.get("version", 0))
            return versions
        except json.JSONDecodeError:
            logger.warning(f"[ReportStore] Corrupted metadata: {meta_file}")
            return []

    async def get_dependencies(
        self,
        session_id: str,
        depends_on: List[str]
    ) -> Dict[str, str]:
        """
        Get dependency reports for a dimension

        Args:
            session_id: Session identifier
            depends_on: List of dependency dimension keys

        Returns:
            Dict mapping dim_key -> latest content
        """
        deps = {}
        for dep_key in depends_on:
            content = await self.get_latest(session_id, dep_key)
            if content:
                deps[dep_key] = content
        return deps


__all__ = ["ReportStore", "ReportVersion"]