"""
Report Store - Report storage with version management

Design:
- Database-backed storage (SQLModel)
- Version history for each dimension
- Lightweight index in state, full content stored in DB
- Supports time-travel (version rollback)
"""

import uuid
import asyncio
import json
import re
from datetime import datetime
from typing import Any, Dict, List, Optional, TypedDict

from sqlmodel import select

from ..database.models import DimensionReport
from ..database.engine import get_async_session
from ..utils.logger import get_logger

logger = get_logger(__name__)


# ==========================================
# TypedDict Definitions
# ==========================================

class ReportVersion(TypedDict):
    """Report version metadata (lightweight, stored in state)"""
    version: int              # 1-based version number
    report_id: str            # UUID generated by save()
    summary: str              # Structured JSON summary
    generated_at: str         # ISO timestamp
    revision_trigger: Optional[str]  # Reason for revision (e.g., "user feedback")


# ==========================================
# ReportStore Class
# ==========================================

class ReportStore:
    """
    Report Storage and Version Management

    Database-backed storage using SQLModel.
    Replaces file-based storage for better query efficiency and consistency.
    """

    _instance: Optional["ReportStore"] = None

    def __init__(self):
        """Initialize report store"""
        logger.info("[ReportStore] Initialized with database backend")

    @classmethod
    def get_instance(cls) -> "ReportStore":
        """Get singleton instance"""
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    async def save(
        self,
        session_id: str,
        dim_key: str,
        version: int,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
        layer: int = 1,
        knowledge_sources: Optional[List[Dict[str, Any]]] = None,
        gis_data: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """
        Save report and return report_id

        Args:
            session_id: Session identifier
            dim_key: Dimension key (e.g., "location", "land_use")
            version: Version number (1-based)
            content: Full report content
            metadata: Optional metadata (revision_reason, etc.)
            layer: Layer number (1/2/3)
            knowledge_sources: RAG knowledge sources
            gis_data: GIS tool results

        Returns:
            report_id: UUID for retrieving the report
        """
        report_id = str(uuid.uuid4())
        summary = await self._generate_summary(content, dim_key, layer)

        db_report = DimensionReport(
            session_id=session_id,
            dimension_key=dim_key,
            layer=layer,
            version=version,
            report_id=report_id,
            content=content,
            summary=summary,
            revision_trigger=metadata.get("revision_reason") if metadata else None,
            knowledge_sources=knowledge_sources,
            gis_data=gis_data,
            generated_at=datetime.now(),
        )

        async with get_async_session() as db:
            db.add(db_report)
            await db.commit()
            await db.refresh(db_report)

        logger.info(f"[ReportStore] Saved: {session_id}/{dim_key}/v{version} (id={report_id[:8]}...)")
        return report_id

    async def bulk_save(self, reports: List[Dict[str, Any]]) -> List[str]:
        """
        批量保存报告（单事务）

        性能优化：将多个报告在一次事务中写入数据库，
        减少 N transactions -> 1 transaction。

        Args:
            reports: 报告数据列表，每个元素包含：
                - session_id: Session identifier
                - dimension_key: Dimension key
                - layer: Layer number
                - version: Version number
                - report_id: UUID
                - content: Full report content
                - summary: Summary text
                - knowledge_sources: Optional RAG sources
                - gis_data: Optional GIS data
                - generated_at: Timestamp

        Returns:
            List of report_ids
        """
        if not reports:
            return []

        async with get_async_session() as db:
            for report_data in reports:
                db_report = DimensionReport(
                    session_id=report_data["session_id"],
                    dimension_key=report_data["dimension_key"],
                    layer=report_data["layer"],
                    version=report_data["version"],
                    report_id=report_data["report_id"],
                    content=report_data["content"],
                    summary=report_data.get("summary", report_data["content"][:500]),
                    revision_trigger=report_data.get("revision_trigger"),
                    knowledge_sources=report_data.get("knowledge_sources"),
                    gis_data=report_data.get("gis_data"),
                    generated_at=report_data.get("generated_at", datetime.now()),
                )
                db.add(db_report)
            await db.commit()

        report_ids = [r["report_id"] for r in reports]
        logger.info(f"[ReportStore] Bulk saved {len(reports)} reports: {[r['dimension_key'] for r in reports]}")
        return report_ids

    async def _generate_summary(self, content: str, dim_key: str = "", layer: int = 1) -> str:
        """
        Generate structured JSON summary preserving key data for downstream use.

        Returns JSON string with: dimension_key, layer, word_count, key_points,
        text_summary, metrics. Falls back to regex extraction on failure.
        """
        if not content:
            return ""

        # Use the new summary generator
        from .modules.summary.generator import generate_structured_summary
        try:
            return await generate_structured_summary(dim_key, layer, content)
        except Exception as e:
            logger.warning(f"[ReportStore] Structured summary failed: {e}")
            # Fallback: regex-only
            from .modules.summary.schema import BaseDimensionSummary
            from .modules.summary.generator import _extract_metrics_regex, _extract_key_points_regex
            metrics = _extract_metrics_regex(content, dim_key)
            key_points = _extract_key_points_regex(content)
            summary = BaseDimensionSummary(
                dimension_key=dim_key, layer=layer,
                word_count=len(content), key_points=key_points[:5],
                text_summary=content[:200], metrics=metrics,
            )
            return summary.model_dump_json(ensure_ascii=False)

    @staticmethod
    def parse_summary(summary: str) -> Dict[str, Any]:
        """Parse summary field, handling both JSON and plain text formats."""
        if not summary:
            return {"summary": ""}
        if summary.strip().startswith('{'):
            try:
                return json.loads(summary)
            except json.JSONDecodeError:
                pass
        return {"summary": summary}
    async def get(self, report_id: str) -> Optional[str]:
        """
        Get full report content by report_id

        Args:
            report_id: UUID from save()

        Returns:
            Full content or None if not found
        """
        async with get_async_session() as db:
            statement = select(DimensionReport).where(
                DimensionReport.report_id == report_id
            )
            result = await db.execute(statement)
            report = result.scalar_one_or_none()

            if report:
                return report.content

        logger.warning(f"[ReportStore] Not found: {report_id[:8]}...")
        return None

    async def get_report(self, report_id: str) -> Optional[DimensionReport]:
        """
        Get full report record by report_id

        Args:
            report_id: UUID from save()

        Returns:
            DimensionReport or None
        """
        async with get_async_session() as db:
            statement = select(DimensionReport).where(
                DimensionReport.report_id == report_id
            )
            result = await db.execute(statement)
            return result.scalar_one_or_none()

    async def get_by_version(
        self,
        session_id: str,
        dim_key: str,
        version: int
    ) -> Optional[str]:
        """
        Get report content by version number

        Args:
            session_id: Session identifier
            dim_key: Dimension key
            version: Version number

        Returns:
            Full content or None
        """
        async with get_async_session() as db:
            statement = select(DimensionReport).where(
                DimensionReport.session_id == session_id,
                DimensionReport.dimension_key == dim_key,
                DimensionReport.version == version,
            )
            result = await db.execute(statement)
            report = result.scalar_one_or_none()

            if report:
                return report.content

        return None

    async def get_latest(
        self,
        session_id: str,
        dim_key: str
    ) -> Optional[str]:
        """
        Get latest version content

        Args:
            session_id: Session identifier
            dim_key: Dimension key

        Returns:
            Full content of latest version or None
        """
        async with get_async_session() as db:
            statement = (
                select(DimensionReport)
                .where(
                    DimensionReport.session_id == session_id,
                    DimensionReport.dimension_key == dim_key,
                )
                .order_by(DimensionReport.version.desc())
            )
            result = await db.execute(statement)
            report = result.scalar_one_or_none()

            if report:
                return report.content

        return None

    async def get_latest_version(
        self,
        session_id: str,
        dim_key: str
    ) -> int:
        """
        Get the latest version number for a dimension.

        Returns 0 if no reports exist (so next_version = latest + 1 = 1).
        """
        async with get_async_session() as db:
            statement = (
                select(DimensionReport.version)
                .where(
                    DimensionReport.session_id == session_id,
                    DimensionReport.dimension_key == dim_key,
                )
                .order_by(DimensionReport.version.desc())
            )
            result = await db.execute(statement)
            version = result.scalar_one_or_none()
            return version if version is not None else 0

    async def get_latest_report(
        self,
        session_id: str,
        dim_key: str
    ) -> Optional[dict]:
        """
        Get latest version report record as dict (avoid DetachedInstanceError)

        Args:
            session_id: Session identifier
            dim_key: Dimension key

        Returns:
            dict with layer, content, knowledge_sources or None
        """
        async with get_async_session() as db:
            statement = (
                select(DimensionReport)
                .where(
                    DimensionReport.session_id == session_id,
                    DimensionReport.dimension_key == dim_key,
                )
                .order_by(DimensionReport.version.desc())
            )
            result = await db.execute(statement)
            report = result.scalar_one_or_none()
            if report:
                return {
                    "layer": report.layer,
                    "content": report.content,
                    "knowledge_sources": report.knowledge_sources or [],
                }
            return None

    async def list_versions(
        self,
        session_id: str,
        dim_key: str
    ) -> List[ReportVersion]:
        """
        List all versions for a dimension

        Args:
            session_id: Session identifier
            dim_key: Dimension key

        Returns:
            List of ReportVersion (sorted by version number)
        """
        async with get_async_session() as db:
            statement = (
                select(DimensionReport)
                .where(
                    DimensionReport.session_id == session_id,
                    DimensionReport.dimension_key == dim_key,
                )
                .order_by(DimensionReport.version)
            )
            result = await db.execute(statement)
            reports = result.scalars().all()

            return [
                ReportVersion(
                    version=r.version,
                    report_id=r.report_id,
                    summary=r.summary,
                    generated_at=r.generated_at.isoformat() + "Z",
                    revision_trigger=r.revision_trigger,
                )
                for r in reports
            ]

    async def get_dependencies(
        self,
        session_id: str,
        depends_on: List[str]
    ) -> Dict[str, str]:
        """
        Get dependency reports for a dimension

        Args:
            session_id: Session identifier
            depends_on: List of dependency dimension keys

        Returns:
            Dict mapping dim_key -> latest content
        """
        deps = {}
        for dep_key in depends_on:
            content = await self.get_latest(session_id, dep_key)
            if content:
                deps[dep_key] = content
        return deps

    async def get_layer_reports(
        self,
        session_id: str,
        layer: int,
        max_retries: int = 3,
        retry_delay: float = 0.5,
    ) -> Dict[str, str]:
        """
        Get all reports for a layer (with retry for SQLite connection issues)

        Args:
            session_id: Session identifier
            layer: Layer number (1/2/3)
            max_retries: Maximum retry attempts for connection errors
            retry_delay: Delay between retries in seconds

        Returns:
            Dict mapping dim_key -> latest content
        """
        for attempt in range(max_retries):
            try:
                async with get_async_session() as db:
                    statement = (
                        select(DimensionReport)
                        .where(
                            DimensionReport.session_id == session_id,
                            DimensionReport.layer == layer,
                        )
                        .order_by(DimensionReport.dimension_key, DimensionReport.version.desc())
                    )
                    result = await db.execute(statement)
                    reports = result.scalars().all()

                    # Keep only latest version per dimension
                    result_dict = {}
                    seen_dims = set()
                    for r in reports:
                        if r.dimension_key not in seen_dims:
                            result_dict[r.dimension_key] = r.content
                            seen_dims.add(r.dimension_key)

                    return result_dict
            except Exception as e:
                if "no active connection" in str(e) or "OperationalError" in str(e):
                    if attempt < max_retries - 1:
                        logger.warning(f"[ReportStore] SQLite connection error, retrying ({attempt + 1}/{max_retries}): {e}")
                        await asyncio.sleep(retry_delay * (attempt + 1))
                    else:
                        logger.error(f"[ReportStore] Failed after {max_retries} retries: {e}")
                        raise
                else:
                    raise
        return {}

    async def get_layer_reports_with_sources(
        self,
        session_id: str,
        layer: int
    ) -> Dict[str, Dict[str, Any]]:
        """
        Get all reports for a layer with knowledge sources

        Args:
            session_id: Session identifier
            layer: Layer number (1/2/3)

        Returns:
            Dict mapping dim_key -> {content, knowledge_sources}
        """
        async with get_async_session() as db:
            statement = (
                select(DimensionReport)
                .where(
                    DimensionReport.session_id == session_id,
                    DimensionReport.layer == layer,
                )
                .order_by(DimensionReport.dimension_key, DimensionReport.version.desc())
            )
            result = await db.execute(statement)
            reports = result.scalars().all()

            # Keep only latest version per dimension
            result_dict: Dict[str, Dict[str, Any]] = {}
            seen_dims = set()
            for r in reports:
                if r.dimension_key not in seen_dims:
                    result_dict[r.dimension_key] = {
                        "content": r.content,
                        "knowledge_sources": r.knowledge_sources or [],
                    }
                    seen_dims.add(r.dimension_key)

            return result_dict

    async def get_layer_summaries(
        self,
        session_id: str,
        layer: int,
    ) -> Dict[str, Dict[str, Any]]:
        """
        Get structured summaries for all dimensions in a layer.

        Returns Dict mapping dim_key -> parsed summary dict.
        Much lighter than get_layer_reports() for cross-layer dependency loading.
        """
        from .modules.summary.parser import parse_summary
        async with get_async_session() as db:
            statement = (
                select(DimensionReport)
                .where(
                    DimensionReport.session_id == session_id,
                    DimensionReport.layer == layer,
                )
                .order_by(DimensionReport.dimension_key, DimensionReport.version.desc())
            )
            result = await db.execute(statement)
            reports = result.scalars().all()

            summaries = {}
            seen_dims = set()
            for r in reports:
                if r.dimension_key not in seen_dims:
                    summaries[r.dimension_key] = parse_summary(r.summary, r.dimension_key, layer)
                    seen_dims.add(r.dimension_key)

            return summaries

    async def delete_session_reports(self, session_id: str) -> int:
        """
        Delete all reports for a session

        Args:
            session_id: Session identifier

        Returns:
            Number of deleted reports
        """
        async with get_async_session() as db:
            statement = select(DimensionReport).where(
                DimensionReport.session_id == session_id
            )
            result = await db.execute(statement)
            reports = result.scalars().all()
            count = len(reports)

            for r in reports:
                db.delete(r)

            await db.commit()

            logger.info(f"[ReportStore] Deleted {count} reports for session {session_id}")
            return count


__all__ = ["ReportStore", "ReportVersion"]
